name: Competition Pipeline Test

on: [push, pull_request]

jobs:
  competition-pipeline-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Setup python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r conda/requirements.txt

    # Step 4: Run Ingestion
    - name: Run ingestion script
      run: |
        mkdir -p sample_result_submission scoring_output
        python ingestion_program/run_ingestion.py \
          --submission test/sample_submission \
          --num-pseudo-experiments 100 \
          --num-of-sets 1

    # Step 5: Run Scoring
    - name: Run scoring script
      run: |
        python scoring_program/run_scoring.py 

    # Step 6: Run Performance Tests
    - name: Run performance test
      run: |
        python3 test/run_performance_test.py \
          --result-file scoring_output/scores.json