name: Full Chain Test

on: [push, pull_request]

jobs:
  run-ingestion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r conda/requirements.txt

    - name: Run ingestion script
      run: |
        mkdir -p sample_result_submission
        mkdir -p scoring_output
        python ingestion_program/run_ingestion.py --submission test/sample_submission --num-pseudo-experiments 100 --num-of-sets 1
        python scoring_program/run_scoring.py 

  check-performace:
    runs-on: ubuntu-latest
    needs: run-ingestion
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run performance test
      run: python3 test/run_performance_test.py scoring_output/score.json